### ISSUE TITLE
Error in writeImpl: Text to be written must be a length-one character vector

### ISSUE THREAD

**Issue by Skourtis** [jardimViniciusC/BioNetStat#1]
Hi, 

When I try to run through the example, loading the c2.cp.v5.2.symbols.gmt file produces the following error:
 Error in writeImpl: Text to be written must be a length-one character vector and prevents the analysis from happening.

How can I fix this? Is this related to the htmltools issues below?

https://github.com/rstudio/htmltools/issues/147

Thank you!

**Comment by jardimViniciusC** [comment]
Sorry for the late answer. This ERROR message was appearing in the previous version of BioNetStat, and I already fixed it.
Please, make sure that you are using a newer version of BNS (higher than 1.10.1). The update should solve the problem.
One observation: To upgrade BioNetStat, first update the Bioconductor version to 3.12 or higher, so the Bioconductor will install the latest version of BioNetStat.

Thank you
